version: '3.8'

services:
    nginx:
        depends_on:
            - app
        restart: always
        image: nginx
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: 'nginx'
        ports:
            - '80:80'
            - '443:443'
            
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'app'
        volumes:
            - .:/usr/src/
            - '/usr/src/node_modules'
        working_dir: /usr/src
        command: sh -c "yarn && yarn sv_build && cl_build && yarn sv_start"
        ports:
            - 3001:3001
            - 3002:3002